### ISSUE TITLE
No reference to which checkWindow() failed in log output

### ISSUE THREAD

**Issue by elgalu** [applitools/Eyes.Protractor#8]
Hi, great tool! today I implemented eyes.protractor 0.0.47 in a Protractor 3.0.0 test project and so far so good.

It would be nice if we could see in the log output which `it()` aka jasmine *spec* description and spec code line (stacktrace) the visual validations failed because as of now the visual validations seem to be executed in bulk at `eyes.close()` time instead of during each `eyes.checkWindow()` which seems good for performance but bad for reporting. 

This is my example output

```
Failures:
1) Finally closes the eyes visual diff tool
  Message:
    Failed: [EYES: TEST FAILED]: 'User Service' of 'Home'. See details at https://eyes.applitools.com/app/sessions/251952528889535 results: {"steps":2,"matches":1,"mismatches":1,"missing":0,"exactMatches":0,"strictMatches":1,"contentMatches":0,"layoutMatches":0,"noneMatches":0,"isNew":false,"sessionId":"251952528889535","url":"https://eyes.applitools.com/app/sessions/251952528889535","isPassed":false}
  Stack: ... some noise here but no reference to which checkWindow() failed

24 specs, 1 failure
Finished in 86.567 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

How can we keep track of it or improve the reporter to include in `results` more check points details like every `stepDescription` and perhaps stacktrace so we can trace back to the test source each failure.

Ideally I would like some more options
* to fail immediately on each check point, i.e. on each `checkWindow()` call
* to just store the screenshots locally and bulk upload after so my functional tests are as fast as without *eyes* but yet I can get notified of failed vdiff in async mode if there were failures. As of now it holds my tests unnecessary on every success case as you can see.

**Comment by zavelevsky** [comment]
@elgalu - thanks!
By default - the result of the visual comparison is reported during eyes.close() as you mentioned - this is due to the fact that only then it is possible to tell if new visual checkpoints were added - or if there are missing checkpoints compared to the current base line.

However - you can override this behavior by either:
1. Add '.then' clause to eyes.checkWindow to examine the result and check whether it's '.asExpected':
```javascript
eyes.checkWindow('step name').then(function(result) {
  //result.asExpected?
})
```
2. calling:
```javascript
eyes.setFailureReport('Immediate');
```
after initializing eyes instance. Then the test will halt after the first failure.

I recommend option no.1 - so your test will be allowed to complete its run.

This will help you in mapping a failure to a specific 'it' clause - a thing which I cannot do as a library that can be called by any test library.

Regarding your second point - of simply storing the screenshots and run a comparison later - we considered a similar idea in the past but comparing the images during the test is important - because if there's a failure we retry and in this way we avoid false negatives as a result of page that isn't ready yet, for example (imagine we take screenshot before all the images in the page were fully rendered). 

If this explanation doesn't satisfy you and you'd still like this kind of feature please let me know and we'll take it into account.

**Comment by elgalu** [comment]
I have to say was greatly impressed that there are already 2 options to achieve what I needed :) awesome!!

Regarding:

> if there's a failure we retry and in this way we avoid false negatives

It makes total sense, I added retry to jasmine specs for exactly the same reason, not for visual testing in mind though but as a general solution to flaky tests:
https://github.com/elgalu/jasminewd/tree/jasmine_retry#added-features-in-this-fork
But I didn't work on it enough to try to put it upstream and is already outdated (only works for jasmine 1.3)
